### ISSUE TITLE
[BUG] Statements are split incorrectly when containing "*"

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/learning-locker-service#11]
1. **Summary** - Corrupted Statements when containing "*"
2. **Bug Details** 
   1. **What?** - Statemtn gets splitted at the wrong position
   2. **Where?** - https://github.com/rwth-acis/learning-locker-service/blob/master/src/main/i5/las2peer/services/learningLockerService/LearningLockerService.java#L77-L78 
   3. **When?/How often?** - When a statement contains "*"
   4. **How?/Current state** - Send a statement that contains a "*" at some point...
3. *(Optional)* **Fixed state** - Get rid of the current solution and use valid json and parse the token/user information out of the statement and remove it from the statement before storing it.

**Comment by FBasels** [comment]
Should be fixed already with #12
